var language = {
    "add1": "请输入兑换码",
    "add2": "兑换成功",
    "add3": "由于BTC近期存在分叉风险，暂停充值提现!",
    "add4": "登录信息过期,重新登录!",
    "add5": "暂未开放购买BCDN!",
    "add6": "执行成功!",
    "add7": "取消成功!",
    "add8": "笔",
    "add9": "审核中",
    "add10": "成功",
    "add11": "已取消",
    "add12": "已驳回",
    "add13": "取消",
    "add14": "现在是非购币时间 请在以下时间段内进行锁定操作<br>早鸟阶段：2017.8.15  08:00－2017.8.17  08：00<br>锁定阶段：2017.8.23  08:00－2017.8.25  08：00<br>ICO阶段： 2017.8.30  08:00－2017.9.30  08：00",
    "add15": "ICO已经全部结束，谢谢参与!",
    "add16": "金额不允许为负数且不能超过余额",
    "add17": "禁止输入非法字符",
    "add18": "用户不存在",
    "add19": "密码错误",
    "add20": "验证码超时,请重新输入",
    "add21": "验证码错误,请重新输入",










    "comm.tips.11" : "请输入密码！",
    "comm.tips.12" : "密码长度不能小于6！",
    "comm.tips.13" : "密码格式错误，密码必须大于等于6位且包含字母和数字！",
    "comm.tips.14" : "密码长度不能大于16！",
    "comm.tips.17" : "两次密码不一致",
    "comm.tips.18" : "友情提示",
    "comm.tips.19" : "确定",
    "comm.tips.25" : "修改成功",
    "msg.tips.3" : "发送验证码",
    "msg.tips.4" : "{0}秒后可重发",
    "msg.tips.6" : "邮箱格式不正确,请重新输入",
    "user.tips.1" : "邮箱账号不能为空",
    "user.tips.5" : "邮箱不能包含空格！",
    "user.tips.6" : "请输入您的邮箱！",
    "user.tips.7" : "邮箱格式错误",
    "user.tips.8" : "含有非法字",
    "user.tips.9" : "邮箱长度应小于100个字",
    "user.tips.10" : "两次输入密码不一致",
    "user.tips.13" : "请输入邮件验证码",
    "user.tips.17" : "输入的密码不一致！",
    "user.tips.25" : "修改成功，请牢记您的登录密码！",
    "user.tips.26" : "请输入提现地址！",
    "user.tips.27" : "请输入提现数量！",
    "user.tips.28" : "请输入邮箱验证码！",
    "user.tips.29" : "余额不足！",
    "user.tips.30" : "您的提现订单已提交，请耐心等待管理员审核 ！",
    "user.tips.31" : "确定取消提现么？",
    "user.tips.35" : "注册成功！",
    "finance.tips.33" : "请选择资产类型！",
    "finance.tips.34" : "请输入数量！",
    "finance.tips.35" : "最小数量为1！",
    "finance.tips.36" : "余额不足！",
    "finance.tips.37" : "请输入价格！",
    "finance.tips.38" : "最小价格为0.000001！",
    "finance.tips.40" : "确定取消PUSH资产吗？",
    "finance.tips.41" : "请输入对方UID！",
    "finance.tips.42" : "确认付款",
    "finance.tips.43" : "PUSH资产",
    "finance.tips.44" : "PUSH价格",
    "finance.tips.45" : "PUSH数量",
    "finance.tips.46" : "付款金额",
    "finance.tips.47" : "立即付款",
    "finance.tips.48" : "请输入正确的UID",
    "ico.tips.1":"当前每支持1{0}可获得{1}{2}",
    "ico.tips.2":"当前{0}余额",
    "ico.tips.3":"立即充值>>",
    "ico.tips.4":"参与{0}数量",
    "ico.tips.5":"获得{0}",
    "ico.tips.6":"立即参与",
    "ico.tips.7":"请输入参与数量！",
    "ico.page.state0":"预热中",
    "ico.page.state1":"锁定中",
    "ico.page.state2":"众筹中",
    "ico.page.state3":"众筹结束"
};