var language = {
    "add1": "Please enter the exchange code",
    "add2": "success",
    "add3": "As the risk of BTC split, it is suspending deposit and withdraw.",
    "add4": "Please login again.",
    "add5": "Not available for purchase",
    "add6": "success",
    "add7": "cancel success",
    "add8": "sum",
    "add9": "under review",
    "add10": "succeed",
    "add11": "canceled",
    "add12": "rejected",
    "add13": "cancel",








    "comm.tips.11" : "Please enter the password!",
    "comm.tips.12" : "The password can’t be less than 6 characters!",
    "comm.tips.13" : "Incorrect password format，the password should be more than 6 characters and include letters and numbers!",
    "comm.tips.14" : "The password should be less than 16 characters!",
    "comm.tips.17" : "The two passwords don't match",
    "comm.tips.18" : "Reminder",
    "comm.tips.19" : "OK",
    "comm.tips.25" : "Success",
    "msg.tips.3" : "send verification code",
    "msg.tips.4" : "{0}send again",
    "msg.tips.6" : " Incorrect email format, please enter again",
    "user.tips.1" : "The email can’t be blank",
    "user.tips.5" : "The email can’t include any space!",
    "user.tips.6" : "Enter your email!",
    "user.tips.7" : "Incorrect email format",
    "user.tips.8" : "include  illegal characters",
    "user.tips.9" : "The email address can’t be more than 100 characters ",
    "user.tips.10" : "Passwords do not match",
    "user.tips.13" : "Please fill in verification code",
    "user.tips.17" : "passwords do not match!!",
    "user.tips.25" : "Password changes successfully, please remember your new password!",
    "user.tips.26" : "Please fill in withdraw address!",
    "user.tips.27" : "Please fill in withdraw quantity!",
    "user.tips.28" : "please fill in verification code!",
    "user.tips.29" : "The balance is insufficient!",
    "user.tips.30" : "Your request has been submitted, please wait for the approval of administrator!",
    "user.tips.31" : "Are you sure to cancel the withdraw？",
    "user.tips.35" : "Registered successfully!",
    "finance.tips.33" : "please choose the asset type!",
    "finance.tips.34" : "please fill in quantity!",
    "finance.tips.35" : "Minimum quantity is 1!",
    "finance.tips.36" : "The balance is insufficient!",
    "finance.tips.37" : "please fill in the price!",
    "finance.tips.38" : "The lowest price is is 0.000001!",
    "finance.tips.40" : "Are you sure to cancel PUSH asset？",
    "finance.tips.41" : "Please fill in receiver’s UID!",
    "finance.tips.42" : "Payment confirm",
    "finance.tips.43" : "PUSH asset",
    "finance.tips.44" : "PUSH price",
    "finance.tips.45" : "PUSH quantity",
    "finance.tips.46" : "payment amount",
    "finance.tips.47" : "make the payment immediately",
    "finance.tips.48" : "Please enter the correct UID",
    "finance.tips.49" : "The quantity must be greater than 0",
    "finance.tips.50" : "Insufficient balance",
    "finance.tips.51" : "Are you sure to cancel?",
    "ico.tips.1":"current support volume 1{0}can get{1}{2}",
    "ico.tips.2":"Current{0}balance",
    "ico.tips.3":"deposit now>>",
    "ico.tips.4":"Quantity {0}",
    "ico.tips.5":"Get {0}",
    "ico.tips.6":" participate now",
    "ico.tips.7":"please fill in participants quantity!",
    "ico.page.state0":"Preheating",
    "ico.page.state1":"Locking",
    "ico.page.state2":"Crowdfunding",
    "ico.page.state3":"End"
};
